#!/usr/bin/env bash

IFS=: read -ra selected < <(
rg --color=always --line-number --no-heading --smart-case "${*:-}" |
  fzf --delimiter : \
  --preview 'bat --color=always {1} --highlight-line {2}' \
)
[ -n "${selected[0]}" ] && echo "${selected[0]}"
