#!/usr/bin/env bash

rg --color=always --line-number --no-heading --smart-case --hidden "${*:-}" |
  fzf --delimiter : \
  --preview 'bat --color=always --style=numbers,changes,rule --highlight-line {2} {1} ' |
  awk -F: '{ print $1 }'

