#!/usr/bin/env bash

if [ -f "$1" ]; then
	CENTER="$2"
	START_LINE="$((CENTER - FZF_PREVIEW_LINES / 2))"
	if ((START_LINE <= 0)); then
		START_LINE=1
	fi
	END_LINE="$((START_LINE + FZF_PREVIEW_LINES - 1))"
	bat "$1" --color=always --style=numbers,changes,rule --line-range="$START_LINE:$END_LINE" --highlight-line="$CENTER"
fi
