#!/usr/bin/env bash

if [ -f "$1" ]; then
  case "$1" in
    *.[1-8]) man "$1" | col -b ;;
    *.csv) cat "$1" | sed s/,/\\n/g ;;
    *) bat "$1" --color=always --line-range=:500 --style=numbers,changes,rule;;
  esac
elif [ -d "$1" ]; then
  lsd -1 --icon=always --color=always -A -X "$1"
fi

