name: Branch Protection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Linear History
        if: github.event_name == 'pull_request'
        run: |
          if git merge-base --is-ancestor ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}; then
            echo "Linear history check passed"
          else
            echo "Linear history check failed. Please rebase your branch with the base branch."
            exit 1
          fi